plugins {
    id 'java-library'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
java.sourceCompatibility = JavaVersion.VERSION_1_8
group = GROUP_ID
version = VERSION

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    implementation libs.slf4j.api
    testRuntimeOnly libs.slf4j.simple
    testImplementation libs.jupiter.api
    testRuntimeOnly libs.jupiter.engine
    testImplementation libs.jmh.core
    testAnnotationProcessor libs.jmh.generator.annprocess

    implementation libs.dreamcat.common
    implementation libs.round.lex

    testImplementation libs.bundles.jackson

    // https://mvnrepository.com/artifact/org.apache.commons/commons-jexl3
    testImplementation "org.apache.commons:commons-jexl3:3.2.1"
    // // https://mvnrepository.com/artifact/ognl/ognl
    testImplementation 'ognl:ognl:3.3.3'
    // https://mvnrepository.com/artifact/com.alibaba/QLExpress
    testImplementation "com.alibaba:QLExpress:3.3.0"
    // https://mvnrepository.com/artifact/com.googlecode.aviator/aviator
    testImplementation 'com.googlecode.aviator:aviator:5.4.1'
}

test {
    useJUnitPlatform()
}

apply from: new File(rootDir, 'gradle/publish.gradle')

jar {
    manifest {
        attributes(
                "Main-Class": "org.dreamcat.round.el.ElScriptLauncher",
        )
    }
}