apply plugin: 'java'

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
java.sourceCompatibility = JavaVersion.VERSION_1_8
group = GROUP_ID
version = VERSION

dependencies {
    implementation project(':')

    implementation libs.dreamcat.common
    runtimeOnly libs.slf4j.simple
}

apply from: new File(rootDir, 'gradle/tasks-jar.gradle')

jar {
    manifest {
        attributes(
                "Main-Class": "org.dreamcat.round.el.ElScriptLauncher",
        )
    }
}